### ISSUE TITLE
Add documentation for Node TLS

### ISSUE THREAD

**Issue by lukasluecke** [whatwedo/dde#2]
`export NODE_EXTRA_CA_CERTS=~/dde/data/reverseproxy/etc/nginx/certs/ca.pem`

**Comment by Ruesa18** [comment]
@lukasluecke 
1) Is this still a concern?
2) Could you elaborate on this matter? 😅 
Does Node need access to the certificate because it handles all the requests by itself instead of a webserver and wants to verify the connection, did I get that right? 
Then it probably still is an issue to be documented - although I would suggest to write it in a general way as in "You can find the SSL certificates under this directory [...] in case you need to mount them in your services"
